### ISSUE TITLE
npm module?

### ISSUE THREAD

**Issue by andreamancuso** [commschamp/cc.ublox.generated#1]
Hi @arobenko 

Sorry for taking more of your time, I just came up with the following question: would it be possible, in theory, to use the generated C++ code into an npm module? Potentially it could expose a parse() function taking a UIntArray and return either null or a POJO equivalent of a Message class instance.
Does that seem like a valid theory?

**Comment by arobenko** [comment]
Sorry, I don't know much about JS in general and npm environment in particular. The [cc.ublox.commsdsl](https://github.com/commschamp/cc.ublox.commsdsl/) project defines UBX protocol using [CommsDSL](https://commschamp.github.io/commsdsl_spec/) schema and uses various code generators from the [commdsl](https://github.com/commschamp/commsdsl) project to generate C++ code for the protocol definition code as well as various bindings to other programming languages. When you pass `-DUBLOX_GEN_SWIG=ON` it will generate [SWIG](https://www.swig.org/) interface definition, which then can be used to generate bindings to other programming languages. However, if I'm not mistaken the JS bindings lack some functionality support, which makes then insufficient. There is also `-DUBLOX_GEN_EMSCRIPTEN=ON` which will generate [emscripten](https://emscripten.org/) bindings. The latter I think you can use with nodejs.

You can read the following documentation pages:
- [WebAssembly Support](https://github.com/commschamp/commsdsl/blob/master/doc/WebAssemblySupport.md)
- [Other Languages Support](https://github.com/commschamp/commsdsl/blob/master/doc/OtherLanguagesSupport.md)
- [commsdsl2emscripten Manual](https://github.com/commschamp/commsdsl/blob/master/doc/Manual_commsdsl2emscripten.md)
- [commsdsl2swig Manual](https://github.com/commschamp/commsdsl/blob/master/doc/Manual_commsdsl2swig.md)

Hope it helps.

**Comment by andreamancuso** [comment]
Thank you!
